# Generated by Django 4.1.7 on 2023-08-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0009_alter_like_post_alter_like_user_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
