# Generated by Django 4.1.7 on 2023-08-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0010_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/done_icon.png', upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
